### Create
POST http://localhost:19090/api/deliveries
Content-Type: application/json

{
  "order-id": "6b38d6f7-1ebd-468a-a350-f511a41eff4e",
  "depart-hub-id": "148de9af-4291-48ae-b69a-faf0460e7e4e",
  "arrive-hub-id": "45e3bbb6-0350-4736-9e58-7a4ca0543855",
  "delivery-address": "Test Delivery Address",
  "recipient-name": "홍길동",
  "recipient-slack-id": "01011112222"
}

### State Update
PATCH http://localhost:19092/api/deliveries/0a2f1fbe-d1f2-48aa-8ca5-1a8380e779b7/status?
    delivery-status=delivered
Content-Type: application/json

### Search
GET http://localhost:19092/api/deliveries
Content-Type: application/json

{
  "delivery-status": "HUB_PENDING"
}

### Read
GET http://localhost:19092/api/deliveries/2922e4e9-9518-4101-b5b5-108505e892f7

### Status Read
GET http://localhost:19092/api/deliveries/a2d41fe1-fb78-45b4-b972-d64d4e50de20/status