
###Login(마스터)
POST http://localhost:19090/api/users/signIn
Content-Type: application/json

{
  "username": "master",
  "password": "Abcd1234!"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.log("accessToken : " + client.global.get("accessToken"));
%}

###Login(배송담당자)
POST http://localhost:19090/api/users/signIn
Content-Type: application/json

{
  "username": "delivery",
  "password": "Abcd1234!"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.log("accessToken : " + client.global.get("accessToken"));
%}

###Login (업체매니저)
POST http://localhost:19090/api/users/signIn
Content-Type: application/json

{
  "username": "manager",
  "password": "Abcd1234!"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.log("accessToken : " + client.global.get("accessToken"));
%}



### 주문 생성 (재고확인- 배송생성 -배송담당자지정 -배송경로 생성(이동정보관리 조회) -슬랙메시지 전송)
POST http://localhost:19090/api/orders
Content-Type: application/json
Authorization: {{accessToken}}

{
  "receiver-company-id": "a3eeebc0-ae47-4c4c-ac76-4f59d26d6faf",
  "product-id": "6e3596ee-479b-4bd1-b3c0-12e731784026",
  "quantity": 1,
  "request-notes": "8월 4일 3시까지는 보내주세요!",
  "recipient-name": "김00",
  "recipient-slack-id": "01011112222"
}

###주문 취소
DELETE http://localhost:19090/api/orders/b62f9764-f5c7-411c-ad4f-f49232956020/cancel
Content-Type: application/json
Authorization: {{accessToken}}

###배송 상태 변경
PATCH http://localhost:19090/api/deliveries/7fa2a896-c0f8-4c01-a635-0ec54a7360d2/status?deliveryStatus=delivered
Content-Type: application/json
Authorization: {{accessToken}}

###배송지 도착 상태 변경
PUT http://localhost:19090/api/delivery-routes
Content-Type: application/json
Authorization: {{accessToken}}

{
  "deliveryId": "ec709f1a-822f-42e2-b3f8-cbe077e5a4b0",
  "arrviedHubId": "0d65b109-ba6a-4193-ad62-07652bf74bb1"
}