###허브생성(init)
POST http://localhost:19090/api/hubs/setting
Content-Type: application/json

###허브이동경로 생성(init)
POST http://localhost:19090/api/routes/setRoute
Content-Type: application/json


### 회원가입(마스터)
POST http://localhost:19090/api/users/signUp
Content-Type: application/json

{
  "username": "master",
  "password": "Abcd1234!",
  "slackId": "010-2234-5678",
  "role": "ROLE_MASTER",
  "hubId": "afd3c207-c492-4f96-b53a-60ef17f5a879"
}

### 회원가입(배송담당자)
POST http://localhost:19090/api/users/signUp
Content-Type: application/json

{
  "username": "delivery",
  "password": "Abcd1234!",
  "slackId": "010-2234-5678",
  "role": "ROLE_DELIVERY_MANAGER",
  "hubId": "afd3c207-c492-4f96-b53a-60ef17f5a879"
}

### 회원가입(업체매니저)
POST http://localhost:19090/api/users/signUp
Content-Type: application/json

{
  "username": "manager",
  "password": "Abcd1234!",
  "slackId": "010-2234-5678",
  "role": "ROLE_COMPANY_MANAGER",
  "hubId": "afd3c207-c492-4f96-b53a-60ef17f5a879"
}

###Login(마스터)
POST http://localhost:19090/api/users/signIn
Content-Type: application/json

{
  "username": "master",
  "password": "Abcd1234!"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.log("accessToken : " + client.global.get("accessToken"));
%}

###Login(배송담당자)
POST http://localhost:19090/api/users/signIn
Content-Type: application/json

{
  "username": "delivery",
  "password": "Abcd1234!"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.log("accessToken : " + client.global.get("accessToken"));
%}

###Login (업체매니저)
POST http://localhost:19090/api/users/signIn
Content-Type: application/json

{
  "username": "manager",
  "password": "Abcd1234!"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.log("accessToken : " + client.global.get("accessToken"));
%}


###업체생성(공급)
POST http://localhost:19090/api/companys
Content-Type: application/json
Authorization: {{accessToken}}

{
  "companyType": "MANUFACTURER",
  "companyName": "manufacturer",
  "companyAddress": "testtest",
  "hubId": "afd3c207-c492-4f96-b53a-60ef17f5a879"
}

###업체생성(수령)
POST http://localhost:19090/api/companys
Content-Type: application/json
Authorization: {{accessToken}}

{
  "companyType": "RECEIVER",
  "companyName": "reciever",
  "companyAddress": "testtest",
  "hubId": "0d65b109-ba6a-4193-ad62-07652bf74bb1"
}


###상품생성
POST http://localhost:19090/api/products
Content-Type: application/json
Authorization: {{accessToken}}

{
  "productName": "랍스터",
  "productDetail": "신선한 랍스터",
  "companyId": "7779d020-aa2e-4145-a807-5256bbe2fd77",
  "productPrice": 30000.0
}

###재고 update
PUT http://localhost:19090/api/stocks/629bd216-ce05-46fe-b0b8-341051ef173e?
    stockQuantity=200
Authorization: {{accessToken}}

{
  "productName": "상품명테스트2",
  "productDetail": "상품내용테스트2",
  "companyId": "4a0ca5db-79f1-4855-9318-4d8c7f858416",
  "productPrice": 30000.0
}


###배송담당자 등록  ( ROLE_DELIVERY_MANAGER)######   managersType( Company | Hub)
POST http://localhost:19090/api/users/delivery-managers
Content-Type: application/json
Authorization: {{accessToken}}

{
  "managersType": "Company"
}


### 주문 생성 (재고확인- 배송생성 -배송담당자지정 -배송경로 생성(이동정보관리 조회) -슬랙메시지 전송)
POST http://localhost:19090/api/orders
Content-Type: application/json
Authorization: {{accessToken}}

{
  "receiver-company-id": "de4cd842-6f4c-48b5-bd4b-7f1ab1d37006",
  "product-id": "3f5e3967-cf5f-4011-b689-f0feed377a74",
  "quantity": 1,
  "request-notes": "8월 4일 3시까지는 보내주세요!",
  "recipient-name": "김00",
  "recipient-slack-id": "01011112222"
}

###주문 취소
DELETE http://localhost:19090/api/orders/b62f9764-f5c7-411c-ad4f-f49232956020/cancel
Content-Type: application/json
Authorization: {{accessToken}}

###배송 상태 변경
PATCH http://localhost:19090/api/deliveries/7fa2a896-c0f8-4c01-a635-0ec54a7360d2/status?deliveryStatus=delivered
Content-Type: application/json
Authorization: {{accessToken}}

###배송지 도착 상태 변경
PUT http://localhost:19090/api/delivery-routes
Content-Type: application/json
Authorization: {{accessToken}}

{
  "deliveryId": "ec709f1a-822f-42e2-b3f8-cbe077e5a4b0",
  "arrviedHubId": "0d65b109-ba6a-4193-ad62-07652bf74bb1"
}