###회원가입
POST http://localhost:19090/api/users/signUp
Content-Type: application/json

{
  "username": "test2",
  "password": "Abcd1234!",
  "slackId": "slack",
  "role": "ROLE_MASTER"
}

###Login
POST http://localhost:19090/api/users/signIn
Content-Type: application/json

{
  "username": "test2",
  "password": "Abcd1234!"
}

