spring:
  application:
    name: gateway-service
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      uri: http://localhost:18088  # Config Server의 주소
      fail-fast: true

service:
  jwt:
    secret-key: "64+F7IiY66as7Jik7ZiV7KCcIO2ZlOydtO2MheyeheuLiOuLpC4="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    use-root-path: true
    urls[0]:
      name: Order Service
      url: /order-service/v3/api-docs
    urls[1]:
      name: Delivery Service
      url: /delivery-service/v3/api-docs
    urls[2]:
      name: Hub Service
      url:  /hub-service/v3/api-docs
    urls[3]:
      name: Company Service
      url: /comp-service/v3/api-docs
    urls[4]:
      name: Slack Service
      url: /slack-service/v3/api-docs
    urls[5]:
      name: AI Service
      url: /ai-service/v3/api-docs
    urls[6]:
      name: User Service
      url: /user-service/v3/api-docs
