server:
  port: 19096

spring:
  application:
    name: ai-service
  config:
    import: application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/aiinterlock


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /ai-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
