server:
  port: 19096

spring:
  application:
    name: aiinterlock
  profiles:
    active: local
  config:
    import: optional:application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/aiinterlock