server:
  port: 19094

spring:
  application:
    name: comp-service
  config:
    import: application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/company


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /comp-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html