server:
  port: 19094

spring:
  application:
    name: company
  profiles:
    active: local
  config:
    import: optional:application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/company