server:
  port: 19092

spring:
  application:
    name: delivery-service
  config:
    import: application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /delivery-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html