server:
  port: 19092

spring:
  application:
    name: delivery
  profiles:
    active: local
  config:
    import: optional:application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery