server:
  port: 19093

spring:
  application:
    name: hub
  profiles:
    active: local
  config:
    import: optional:application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/hub