server:
  port: 19091

spring:
  application:
    name: order
  profiles:
    active: local
  config:
    import: optional:application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/order