server:
  port: 19095

spring:
  application:
    name: slack
  profiles:
    active: local
  config:
    import: optional:application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/slack