server:
  port: 19095

spring:
  application:
    name: slack-service
  config:
    import: application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/slack

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /slack-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html