server:
  port: 19097

spring:
  application:
    name: user
  profiles:
    active: local
  config:
    import: optional:application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/user