server:
  port: 19097

spring:
  application:
    name: user-service
  config:
    import: application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/users

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /user-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html