### Slack Create
POST http://localhost:19095/api/slacks
Content-Type: application/json

{
  "order-id": "12345678-9e53-48c4-bbc7-2425ec691888",
  "depart-hub-name":"수원 허브",
  "transit-point":"천안 허브",
  "arrive-hub-name":"대전 허브",
  "delivery-address":"대전광역시 중구",
  "recipient-name": "문고은",
  "recipient-slack-id":"01012345678",
  "company-delivery-manager":"김민경",
  "product-name": "랍스터 3kg",
  "product-quantity": 3,
  "request-notes": "긴급! 빠른배송 부탁드립니다.",
  "send-status": "SEND_SUCCESS"
}

### Slack Read
GET http://localhost:19095/api/slacks?page=0&size=10&sort=DESC&orderby=CREATED
Content-Type: application/json

### Slack Search
GET http://localhost:19095/api/slacks/search?page=0&size=10&sort=DESC&orderby=CREATED
Content-Type: application/json

{
    "transit-point": "천안 허브",
    "company-delivery-manager": "김민경"
}


### Slack Update
PATCH http://localhost:19095/api/slacks/status
Content-Type: application/json

{
  "order-id": "12345678-9e53-48c4-bbc7-2425ec691710",
  "send-status": "SEND_FAILURE"
}

### Slack Delete
DELETE http://localhost:19095/api/slacks/delete/8210a620-dbdd-4594-99d2-131c7870b543