### Slack Create
POST http://localhost:19090/api/slacks
Content-Type: application/json
Authorization: {{accessToken}}

{
  "order-id": "12345678-9e53-48c4-bbc7-2425ec611111",
  "depart-hub-name":"수원 허브",
  "transit-point":"천안 허브",
  "arrive-hub-name":"대전 허브",
  "delivery-address":"대전광역시 중구",
  "recipient-name": "문고은",
  "recipient-slack-id":"01012345678",
  "company-delivery-manager":"김민경",
  "product-name": "랍스터 3kg",
  "product-quantity": 3,
  "request-notes": "긴급! 빠른배송 부탁드립니다."
}

### Slack Read
GET http://localhost:19090/api/slacks?page=0&size=10&sort=DESC&orderby=CREATED
Authorization: {{accessToken}}

### Slack Search
GET http://localhost:19090/api/slacks/search?page=0&size=10&sort=DESC&orderby=CREATED
Content-Type: application/json
Authorization: {{accessToken}}

{
    "transit-point": "천안 허브",
    "company-delivery-manager": "김민경"
}


### Slack Update
PATCH http://localhost:19090/api/slacks/status
Content-Type: application/json
Authorization: {{accessToken}}

{
  "order-id": "a1b48aaf-9e53-48c4-bbc7-2425ec691741",
  "send-status": "SEND_FAILURE"
}

### Slack Delete
DELETE http://localhost:19090/api/slacks/delete/d5a65465-9e00-4490-b109-bf125f3a9d23
Authorization: {{accessToken}}