### Create
POST http://localhost:19091/api/orders
Content-Type: application/json

{
  "receiver-company-id": "f376eebc-0bc7-471f-9728-f17376cb1126",
  "product-id": "94e1e613-740c-4e86-ac1d-45926deef242",
  "quantity": 500,
  "request-notes": "12월 12일 3시까지는 보내주세요!",
  "recipient-name": "홍길동",
  "recipient-slack-id": "01011112222"
}

### Read
GET http://localhost:19091/api/orders/6b38d6f7-1ebd-468a-a350-f511a41eff4e
Content-Type: application/json


### Search
GET http://localhost:19091/api/orders
Content-Type: application/json

{
  "receiver-company-id": "1350d08b-0c96-41fd-8d7e-2d56f4461f81"
}

### Update
PATCH http://localhost:19091/api/orders/6b38d6f7-1ebd-468a-a350-f511a41eff4e
Content-Type: application/json

{
  "quantity": 9
}

### Delete
DELETE http://localhost:19091/api/orders/cb20a8b7-7c16-4acc-ae48-922a055ee167