spring:
  application:
    name: eureka-server

server:
  port: 18080


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:18080/eureka/
  instance:
    host-name: localhost

