### 이동경로 생성
POST http://localhost:19093/api/routes
Content-Type: application/json

{
  "departHubId": "afd3c207-c492-4f96-b53a-60ef17f5a879",
  "arriveHubId": "fbca1ccf-ed40-4314-b2ed-ee5bf75cc2b3"
}

### 최단경로
GET http://localhost:19093/api/routes
Content-Type: application/json

{
  "arriveHubId": "afd3c207-c492-4f96-b53a-60ef17f5a879",
  "departHubId": "dccef607-e036-47c2-92b6-a29cf684235a"
}