###Hub Setting
POST http://localhost:19090/api/hubs/setting
Content-Type: application/json

###
POST http://localhost:19090/api/routes/setRoute
Content-Type: application/json

###Hub Create
POST http://localhost:19090/api/hubs/create
Content-Type: application/json
Authorization:

{
  "hubName": "경기 남부 센터",
  "address": "경기도 이천시 덕평로 257-21",
  "latitude": 0,
  "longitude": 0
}

###Hub Create2
POST http://localhost:19090/api/hubs/create
Content-Type: application/json
Authorization:

{
  "hubName": "경기 북부 센터",
  "address": "경기도 고양시 덕양구 권율대로 570",
  "latitude": 0,
  "longitude": 0
}

###Hub 단 건 조회
GET http://localhost:19090/api/hubs/read?id=afd3c207-c492-4f96-b53a-60ef17f5a879
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoidGVzdDIiLCJyb2xlIjoiUk9MRV9NQVNURVIiLCJleHAiOjE3NDI1NjQ4NTksImlhdCI6MTc0MjU2NDI1OX0.-AGvGp7THX-kv1Flkk2MftQdKCMd6k7UxYIB_M6yQMc

###Hub 수정
PATCH http://localhost:19090/api/hubs/update/ca1eaf30-77c8-4d27-9532-d3cda0b31bad
Content-Type: application/json

{
  "hubName": "경기 북부 센터"
}

###Hub 전체조회
GET http://localhost:19090/api/hubs/search?page=0&size=10&sort=createdAt,asc&hubName=경기
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoidGVzdDIiLCJyb2xlIjoiUk9MRV9NQVNURVIiLCJleHAiOjE3NDI1NjY5NjUsImlhdCI6MTc0MjU2NjM2NX0.Q6UBEQHl1rNytXTVil2FIRGWR3AmQTblZRIEfg2OnPA
